site_name: NSI terminale
theme:
  name: material
  favicon: img/favicon.png
  language: fr
  palette:
    primary: black
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 'Partie 1':
    - 'C1 : Introduction':
      - 'Cours': 'c1c.md'
      - 'Activités' : 'c1a.md'
      - 'Révision' : 'c1r.md'
    - 'C2 : bd relationnelles':
      - 'Cours': 'c2c.md'
      - 'Activités' : 'c2a.md'
      - 'Exercices' : 'c2e.md'
      - 'Révision' : 'c2r.md'
    - 'C3 : langage SQL':
      - 'Cours': 'c3c.md'
      - 'Activités' : 'c3a.md'
      - 'Exercices' : 'c3e.md'
      - 'Révision' : 'c3r.md'
  - 'Partie 2':
    - 'C4 : récursivité':
      - 'Cours': 'c4c.md'
      - 'Activités' : 'c4a.md'
      - 'Exercices' : 'c4e.md'
      - 'Révision' : 'c4r.md'
    - 'C5 : listes-piles-files':
      - 'Cours': 'c5c.md'
      - 'Activités' : 'c5a.md'
      - 'Exercices' : 'c5e.md'
      - 'Révision' : 'c5r.md'
    - 'C6 : les dictionnaires':
      - 'Cours': 'c6c.md'
      - 'Activités' : 'c6a.md'
      - 'Exercices' : 'c6e.md'
      - 'Révision' : 'c6r.md'
    - 'C7 : les arbres':
      - 'Cours': 'c7c.md'
      - 'Activités' : 'c7a.md'
      - 'Exercices' : 'c7e.md'
      - 'Révision' : 'c7r.md'
    - 'C8 : algo arbres binaires':
      - 'Cours': 'c8c.md'
      - 'Activités' : 'c8a.md'
      - 'Exercices' : 'c8e.md'
      - 'Révision' : 'c8r.md'
    - '*C9 : les graphes':
      - 'Cours': 'c9c.md'
      - 'Activités' : 'c9a.md'
      - 'Exercices' : 'c9e.md'
      - 'Révision' : 'c9r.md'
    - '*C10 : algo graphes':
      - 'Cours': 'c10c.md'
      - 'Activités' : 'c10a.md'
      - 'Exercices' : 'c10e.md'
      - 'Révision' : 'c10r.md'
  - 'Partie 3':
    - 'C11 : protocoles de routage':
      - 'Cours': 'c11c.md'
      - 'Activités' : 'c11a.md'
      - 'Exercices' : 'c11e.md'
      - 'Révision' : 'c11r.md'
    - '*C12 : sécurisation des communications':
      - 'Cours': 'c12c.md'
      - 'Activités' : 'c12a.md'
      - 'Exercices' : 'c12e.md'
      - 'Révision' : 'c12r.md'
  - 'Partie 4':
    - '*C13 : calculabilité-décidabilité':
      - 'Cours': 'c13c.md'
      - 'Activités' : 'c13a.md'
      - 'Exercices' : 'c13e.md'
      - 'Révision' : 'c13r.md'
    - 'C14 : paradigmes de programmation':
      - 'Cours': 'c14c.md'
      - 'Activités' : 'c14a.md'
      - 'Exercices' : 'c14e.md'
      - 'Révision' : 'c14r.md'
  - 'Partie 5':
    - 'C15 : méthode diviser pour régner':
      - 'Cours': 'c15c.md'
      - 'Activités' : 'c15a.md'
      - 'Exercices' : 'c15e.md'
      - 'Révision' : 'c15r.md'
    - '*C16 : programmation dynamique':
      - 'Cours': 'c16c.md'
      - 'Activités' : 'c16a.md'
      - 'Exercices' : 'c16e.md'
      - 'Révision' : 'c16r.md'
    - '*C17 : recherche textuelle':
      - 'Cours': 'c17c.md'
      - 'Activités' : 'c17a.md'
      - 'Exercices' : 'c17e.md'
      - 'Révision' : 'c17r.md'
  - 'Partie 6':
    - '*C18 : système sur puce':
      - 'Cours': 'c18c.md'
      - 'Activités' : 'c18a.md'
      - 'Exercices' : 'c18e.md'
      - 'Révision' : 'c18r.md'
    - 'C19 : les processus':
      - 'Cours': 'c19c.md'
      - 'Activités' : 'c19a.md'
      - 'Exercices' : 'c19e.md'
      - 'Révision' : 'c19r.md'
  - 'Projets' :
    - 'Projet 1 : répertoire téléphonique' : 'pr1.md'
    - 'Projet 2 : jeu du morpion' : 'pr2.md'
  
  
  
